[package]
name = "light-defender-client"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
rsa = "0.9.6"
serde = { version = "1.0.219", features=["derive"]}
serde_json = "1.0.143"
tokio = { version = "1.47.1", features=["full"]}
uuid = { version = "1.18.0", features = ["serde"] }

